### ISSUE TITLE
Add , please , list of free C++ online courses

### ISSUE THREAD

**Issue by skillcombo** [RedSkittleFox/Cpp-Learning-Resources#2]
I think this list of free courses https://skillcombo.com/topic/c-plus-plus/free/ will be helpful for the community

**Comment by RedSkittleFox** [comment]
This is against the spirit of this document. It's meant to be a concrete collection of materials. This resource is not that it's a link to a *shady* online course browser. If you have some specific courses you would like to be included here, please post a link to the course directly on the original website where it has been published. 

Also, if you're going to advertise your website like that, please host it on something better than the Raspberry Pi and make sure it's responsive. As it is, that website is unusable.
